line.bot.channel-secret=16074c8b832f495133aef76bdca63626
line.bot.channel-token=nHnXMtydl6l3fscwW1atBEbRcNfaZmV5t3qjm4RMMAzeDsw7IJDIwcTZkkRdCEdq979YWi/CXZ3Ibs09G3BQFWUKLKLqI9R3vFpjam3PpEWBsV7ODTuizPBcWo6vccjYCU9iTVWzyEdklNGld8AdtwdB04t89/1O/w1cDnyilFU=
line.bot.handler.path=/callback
